language: php

php:
    - 7.2

before_script:
    - "composer selfupdate"
    - "composer --version"
    - "composer install --prefer-dist --verbose"

script:
  - cd tests && phpunit --coverage-text

