language: php

php:
    - 5.5
    - 5.6

before_script:
    - "composer selfupdate"
    - "composer --version"
    - "composer install --prefer-dist --verbose"

script:
  - cd tests && phpunit --coverage-text
